[package]
name = "stellar"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
color-eyre = "0.6.5"
egui = { version = "0.33.3", features = ["bytemuck"] }
egui-winit = "0.33.3"
env_logger = "0.11.9"
eyre = "0.6.12"
log = "0.4.29"
pollster = "0.4.0"
type-map = "0.5.1"
wgpu = "28.0.0"
winit = { version = "0.30.12" }
